subdir('Optimize')
subdir('Occsat')

install_data(
	[
		'bitx.lua',
		'build.lua',
		'check.lua',
		'graph.lua',
		'id_store.lua',
		'init.lua',
		'misc.lua',
		'ordered_map.lua',
		'plan.lua',
		'plot.lua',
		'runner.lua',
		'strict.lua',
		'testbed.lua',
		'user_node.lua',
	],
	install_dir: module_install_dir,
)
